### ISSUE TITLE
Sample Input File?

### ISSUE THREAD

**Issue by sjohnson76** [omidshy/aMD#1]
Hello!

I tried to use this code with a gromacs output formatted as specified in the code; however, it is not working. Do you have a sample output code so I can check that my formatting is correct?

Thank you!

Sam

**Comment by omidshy** [comment]
Hi Sam,

I have included a sample data file under `example/press.data`. I've also updated the autocorrelation code which makes the calculations using the Green-Kubo approach much faster.

For more information regarding the calculation of the viscosity you can check the following paper:
[doi.org/10.1021/acs.jpcb.1c10671](https://doi.org/10.1021/acs.jpcb.1c10671)
